Repository php-etl/documentation, pull requests merged in 2024-01, with the labels that each got.

#70 Fixed composer require commands
  content/connectivity/akeneo/plugin.en.md
  content/connectivity/csv/_index.en.md
  content/connectivity/fast-map/_index.en.md
  content/connectivity/json/_index.en.md
  content/connectivity/magento-2/_index.en.md
  content/connectivity/prestashop/_index.en.md
  content/connectivity/spreadsheet/_index.en.md
  content/connectivity/sql/_index.en.md
  content/connectivity/sylius/_index.en.md
  content/connectivity/zoho/_index.en.md
  content/core-concept/satellite/action/index.en.md
  content/core-concept/satellite/workflow/_index.en.md
  content/getting-started/installation/_index.en.md
Labels: GTM

#68 Added the use of a necessary code for each job in a workflow
  content/core-concept/satellite/workflow/_index.en.md
Labels: GTM, new

#59 Custom connectors: show how to use a factory and a method call
  content/connectivity/custom/_index.en.md
  content/feature/services/_index.en.md
Labels: WIP

#72 Changed the location of the cloud doc + added more details
  config.toml
  content/cloud/usage/_index.en.md
  content/core-concept/satellite/_index.en.md
Labels: GTM

#73 The public option is no longer necessary for the service declared in the use option
  content/connectivity/custom/_index.en.md
  content/core-concept/satellite/action/index.en.md
Labels: GTM

#71 Add copy's section to the core page of the documentation
  content/core-concept/satellite/_index.en.md
Labels: WIP
